name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - voila
  - kagglehub
  - ipywidgets
  - pandas
  - matplotlib
  - ipympl
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
